FROM confluentinc/cp-kafka-connect:5.2.1

RUN curl https://repo1.maven.org/maven2/io/debezium/debezium-connector-postgres/0.9.5.Final/debezium-connector-postgres-0.9.5.Final-plugin.tar.gz | tar -xz  -C /usr/share/java/