apiVersion: v1
kind: Service
metadata:
  labels:
    app: nifi
  name: nifi
spec:
  ports:
  - port: 8080
    name: ui
    targetPort: ui
    protocol: TCP
  - port: 9001
    name: dealers-push
    targetPort: dealers-push
    protocol: TCP
  - port: 9002
    name: last-update
    targetPort: last-update
    protocol: TCP
  - port: 10001
    name: dealers-pull
    targetPort: dealers-pull
    protocol: TCP
  - port: 10002
    name: vehicles-pull
    targetPort: vehicles-pull
    protocol: TCP
  - port: 10003
    name: hybris-push
    targetPort: hybris-push
    protocol: TCP
  selector:
    app: nifi
  sessionAffinity: None
  type: ClusterIP