apiVersion: v1
kind: Service
metadata:
  labels:
    app: nifi
  name: nifi-headless
spec:
  clusterIP: None
  ports:
  - name: ui
    port: 8080
    protocol: TCP
    targetPort: ui
  - name: rest
    port: 9090
    protocol: TCP
    targetPort: rest
  selector:
    app: nifi
  sessionAffinity: None
  type: ClusterIP