apiVersion: v1
kind: Service
metadata:
  name: nifi-external
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: ui
  - port: 9090
    protocol: TCP
    targetPort: 9090
    name: client
  - port: 9091
    protocol: TCP
    targetPort: 9091
    name: api1
  - port: 9092
    protocol: TCP
    targetPort: 9092
    name: api2
  - port: 9093
    protocol: TCP
    targetPort: 9093
    name: api3
  selector:
    app: nifi