apiVersion: v1
kind: Service
metadata:
  labels:
    app: nifi
  name: nifi
spec:
  ports:
  - name: ui
    port: 8080
    protocol: TCP
    targetPort: ui
  - name: rest
    port: 9090
    protocol: TCP
    targetPort: rest
  - name: api1
    port: 9091
    protocol: TCP
    targetPort: api1
  - name: api2
    port: 9092
    protocol: TCP
    targetPort: api2
  - name: api3
    port: 9093
    protocol: TCP
    targetPort: api3
  selector:
    app: nifi
  sessionAffinity: None
  type: ClusterIP