apiVersion: v1
kind: List
items:
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    name: nifi-network-policy
  spec:
    podSelector:
      matchLabels:
        app: nifi
    ingress:
    - {}