apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafkap-eai-deployment
  namespace: garagetest
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafkap-eai-app
    spec:
      containers:
      - name: kafkap-eai-container
        image: "reg-dhc-americas.app.corpintra.net/myanama/kafka-publisher:1.0.0"
        ports:
        - containerPort: 9005
      securityContext:
        fsGroup: 9999
        runAsUser: 1000
        supplementalGroups:
        - 9999
---
apiVersion: v1
kind: Service
metadata:
  name: kafkap-eai-service
  namespace: garagetest
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9005
  selector:
    app: kafkap-eai-app
---
kind: NetworkPolicy
apiVersion: extensions/v1beta1
metadata:
  name: kafkap-eai-networkpolicy
  namespace: garagetest
spec:
  podSelector:
    matchLabels:
      app: kafkap-eai-app
  ingress:
    - ports:
      - port: 9005
        protocol: TCP
    - from:
      - namespaceSelector:
          matchLabels:
            name: ingress
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kafkap-eai-ingress
  namespace: garagetest
  annotations:
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - http:
      paths:
      - path: /qa/kafka1
        backend:
          serviceName: kafkap-eai-service
          servicePort: 80
