apiVersion: v1
kind: Pod
metadata:
  name: kafka-client
  namespace: default
spec:
  containers:
  - name: kafka-client
    image: reg-dhc-americas.app.corpintra.net/myanama/cp-enterprise-kafka:5.2.1
    command:
      - sh
      - -c
      - "exec tail -f /dev/null"