apiVersion: v1
kind: Pod
metadata:
  name: zookeeper-client
  namespace: default
spec:
  containers:
  - name: zookeeper-client
    image: reg-dhc-americas.app.corpintra.net/myanama/cp-zookeeper:5.0.1
    command:
      - sh
      - -c
      - "exec tail -f /dev/null"