apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kibana-ingress
  annotations:
    traefik.frontend.rule.type: PathPrefixStrip
    ingress.kubernetes.io/content-type-nosniff: "true"
    nginx.ingress.kubernetes.io/affinity: cookie
spec:
  rules:
  - http:
      paths:
      - path: /app/kibana
        backend:
          serviceName: kibana-external
          servicePort: 80