apiVersion: v1
kind: Service
metadata:
  labels:
    app: kibana
  name: kibana-headless
spec:
  clusterIP: None
  ports:
  - name: client
    port: 5601
    protocol: TCP
    targetPort: client
  selector:
    app: kibana
  sessionAffinity: None
  type: ClusterIP