kubectl create --namespace garagetest -f - <<EOF 
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: i3:helm:serviceaccount
rules:
- apiGroups:
  - networking.k8s.io
  - extensions
  resources:
  - networkpolicies
  verbs:
  - create
  - get
  - delete
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: i3:helm:serviceaccount
subjects:
  - kind: ServiceAccount
    name: i3-helm
    namespace: default
roleRef:
  kind: Role
  name: i3:helm:serviceaccount
  apiGroup: rbac.authorization.k8s.io
EOF