apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgresmaster
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: postgresmaster
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
  # delete is required only for 'patronictl remove'
  - delete
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - patch
  - update
  # the following three privileges are necessary only when using endpoints
  - create
  - list
  - watch
  # delete is required only for for 'patronictl remove'
  - delete
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - patch
  - update
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: postgresmaster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: postgresmaster
subjects:
- kind: ServiceAccount
  name: postgresmaster
