apiVersion: v1
kind: Service
metadata:
  labels:
    app: elasticsearch
  name: elasticsearch-headless
spec:
  clusterIP: None
  ports:
  - name: client
    port: 9200
    protocol: TCP
    targetPort: client
  - name: server
    port: 9300
    protocol: TCP
    targetPort: server
  selector:
    app: elasticsearch
  sessionAffinity: None
  type: ClusterIP