apiVersion: v1
kind: Service
metadata:
  labels:
    app: elasticsearch
  name: elasticsearch
spec:
  ports:
  - name: client
    port: 9200
    protocol: TCP
    targetPort: client
  selector:
    app: elasticsearch
  sessionAffinity: None
  type: ClusterIP