apiVersion: v1
kind: Pod
metadata:
  name: kafka-client
spec:
  securityContext: 
    runAsUser: 1000
  containers:
  - name: kafka-client
    image: reg-dhc-americas.app.corpintra.net/myanama/kafka:2.1.0
    command:
      - sh
      - -c
      - "exec tail -f /dev/null"
